#!/bin/bash
vagrant up
ip_address=$(vagrant ssh-config | grep HostName | awk '{print $2}')
echo "Host available under $ip_address"
rm ./data/helloworld.txt
original_dir=$(pwd)
temp_dir=$(mktemp -d)
cd "$temp_dir"
echo "Use the password \"vagrant\"."
git clone root@"$ip_address":/root/control.git 
cd control
mkdir manifests
cp "$original_dir"/example/manifests/hello.pp manifests/hello.pp
cat << 'PUPPET' > Puppetfile
forge 'forge.puppetlabs.com'
mod 'puppetlabs/stdlib'
mod 'puppet-nginx', '7.0.1'
PUPPET

git add Puppetfile
git add manifests/hello.pp
git commit -m "feat: test commit"
echo "Use the password \"vagrant\"."
git_output=$(git push origin main 2>&1)
echo "$git_output"
if echo "$git_output" | grep -q "Success: 1"; then
    echo "Success: The post receive hook was executed. "
else
    echo "No success: The expected output was not found."
fi
cd ..
rm -r "$temp_dir"
cd "$original_dir"
vagrant destroy
